# Generated by Django 2.1.2 on 2018-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StickerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='slab',
            old_name='slab_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sticker',
            name='slab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slab.Slab'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slab.StickerType'),
        ),
    ]
