# Generated by Django 2.1.2 on 2018-10-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0002_auto_20181019_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='text',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
