# Generated by Django 2.1.2 on 2018-10-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0003_sticker_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slab',
            name='public',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='type',
        ),
        migrations.AddField(
            model_name='slab',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sticker',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='StickerType',
        ),
    ]
