# Generated by Django 2.1.2 on 2018-10-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0004_auto_20181023_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='x',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='y',
        ),
    ]
