# Generated by Django 2.1.2 on 2018-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0005_auto_20181026_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
