# Generated by Django 2.1.2 on 2018-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0006_auto_20181029_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
