# Generated by Django 2.1.2 on 2018-10-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0007_uploadedimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='color',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
