# Generated by Django 2.1.2 on 2018-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0008_sticker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='color',
            field=models.CharField(max_length=8),
        ),
    ]
