# Generated by Django 2.1.2 on 2018-11-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0012_auto_20181101_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='position_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sticker',
            name='position_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slab',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
