# Generated by Django 2.1.2 on 2018-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slab', '0013_auto_20181106_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='font',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
